[build]
  publish = "site"
  functions = "functions"
  command = "cd src && npm install -g netlify-lambda && npm install && cd .. && netlify-lambda build src"

[[redirects]]
  from = "http://rodric.io/*"
  to = "https://rabbah.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://rodric.io/*"
  to = "https://rabbah.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://rabbahs.com/*"
  to = "https://rabbah.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://rabbahs.com/*"
  to = "https://rabbah.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://rodric.rabbahs.com/*"
  to = "https://rabbah.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://rodric.rabbahs.com/*"
  to = "https://rabbah.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/.netlify/functions/hello"
  status = 200
  force = false

[[redirects]]
  from = "/index.html"
  to = "/.netlify/functions/hello"
  status = 200
  force = false

[[redirects]]
  from = "/hello.html"
  to = "/.netlify/functions/hello"
  status = 200
  force = false

[[redirects]]
  from = "/publications.html"
  to = "/.netlify/functions/publications"
  status = 200
  force = false

[[redirects]]
  from = "/patents.html"
  to = "/.netlify/functions/patents"
  status = 200
  force = false

[[redirects]]
  from = "/openwhisk.html"
  to = "/.netlify/functions/openwhisk"
  status = 200
  force = false

[[redirects]]
  from = "/research.html"
  to = "/.netlify/functions/research"
  status = 200
  force = false

[[redirects]]
  from = "/software-and-artifacts.html"
  to = "/.netlify/functions/software"
  status = 200
  force = false

[[redirects]]
  from = "/software.html"
  to = "/.netlify/functions/software"
  status = 200
  force = false

[[redirects]]
  from = "/cv"
  to = "/uploads/rabbah-cv.pdf"
  status = 301
  force = false
