[build]
  publish = "site"
  functions = "functions"
  command = "cd src && npm install -g netlify-lambda && npm install && cd .. && netlify-lambda build src"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/hello"
  status = 301
  force = false
