[build]
  publish = "site"
  functions = "functions"
  command = "cd src && npm install -g netlify-lambda && npm install && cd .. && netlify-lambda build src"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/hello"
  status = 301
  force = false

[[redirects]]
  from = "/hello.html"
  to = "/.netlify/functions/hello"
  status = 301
  force = false

[[redirects]]
  from = "/index.html"
  to = "/.netlify/functions/hello"
  status = 301
  force = false

[[redirects]]
  from = "/publications.html"
  to = "/.netlify/functions/publications"
  status = 301
  force = false

[[redirects]]
  from = "/patents.html"
  to = "/.netlify/functions/patents"
  status = 301
  force = false

[[redirects]]
  from = "/openwhisk.html"
  to = "/.netlify/functions/openwhisk"
  status = 301
  force = false

[[redirects]]
  from = "/research.html"
  to = "/.netlify/functions/research"
  status = 301
  force = false

[[redirects]]
  from = "/software-and-artifacts.html"
  to = "/.netlify/functions/software"
  status = 301
  force = false

[[redirects]]
  from = "/software.html"
  to = "/.netlify/functions/software"
  status = 301
  force = false
